import { Recipe } from '../types/recipe';

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'rec_creamy_garlic_chicken_01',
    title: 'Creamy Garlic Butter Tuscan Chicken',
    slug: 'creamy-garlic-butter-tuscan-chicken',
    shortDescription:
      'Pan-seared golden chicken breasts simmered in a rich garlic butter cream sauce with sun-dried tomatoes and baby spinach.',
    introduction:
      'This restaurant-quality Tuscan Chicken is a weeknight lifesaver. Tender, golden chicken cutlets are enveloped in a velvety parmesan and sun-dried tomato sauce that comes together in just 30 minutes in a single skillet.',
    ingredients: [
      { id: '1', rawText: '2 large boneless skinless chicken breasts, sliced horizontally into 4 cutlets', item: 'Chicken cutlets', quantity: 2, unit: 'breasts' },
      { id: '2', rawText: '1 tbsp olive oil', item: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { id: '3', rawText: '2 tbsp unsalted butter', item: 'Butter', quantity: 2, unit: 'tbsp' },
      { id: '4', rawText: '6 cloves garlic, minced', item: 'Garlic', quantity: 6, unit: 'cloves' },
      { id: '5', rawText: '1/2 cup oil-packed sun-dried tomatoes, drained and sliced', item: 'Sun-dried tomatoes', quantity: 0.5, unit: 'cup' },
      { id: '6', rawText: '1 cup heavy whipping cream', item: 'Heavy cream', quantity: 1, unit: 'cup' },
      { id: '7', rawText: '1/2 cup chicken broth', item: 'Chicken broth', quantity: 0.5, unit: 'cup' },
      { id: '8', rawText: '1/2 cup freshly grated Parmesan cheese', item: 'Parmesan cheese', quantity: 0.5, unit: 'cup' },
      { id: '9', rawText: '2 cups fresh baby spinach', item: 'Baby spinach', quantity: 2, unit: 'cups' },
      { id: '10', rawText: '1 tsp Italian seasoning', item: 'Italian seasoning', quantity: 1, unit: 'tsp' },
      { id: '11', rawText: 'Salt and freshly cracked black pepper to taste', item: 'Salt and pepper' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Season and Sear Chicken',
        instructionText: 'Season chicken cutlets generously with salt, black pepper, and Italian seasoning. Heat olive oil and 1 tbsp butter in a large skillet over medium-high heat. Sear chicken for 4-5 minutes per side until golden brown and cooked through (165°F). Transfer to a plate.',
        tip: 'Pat chicken dry with paper towels before seasoning for the crispiest golden crust.',
      },
      {
        stepNumber: 2,
        title: 'Sauté Aromatics',
        instructionText: 'In the same skillet, melt remaining 1 tbsp butter over medium heat. Add minced garlic and sun-dried tomatoes. Sauté for 1 minute until fragrant.',
      },
      {
        stepNumber: 3,
        title: 'Build the Cream Sauce',
        instructionText: 'Pour in chicken broth and heavy cream, scraping up any browned bits from the bottom of the skillet. Bring to a gentle simmer for 3 minutes until slightly thickened. Stir in grated Parmesan until smooth.',
      },
      {
        stepNumber: 4,
        title: 'Wilt Spinach & Combine',
        instructionText: 'Add fresh spinach and simmer for 1-2 minutes until wilted. Return chicken and rested juices back to the skillet, spooning sauce over the top. Serve immediately.',
      },
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    totalTimeMinutes: 30,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Italian-American',
    mealType: 'dinner',
    cookingMethod: 'stovetop',
    primaryCategorySlug: 'chicken',
    categorySlugs: ['chicken', 'quick-and-easy', '30-minute-meals'],
    tags: ['chicken', '30-minute', 'skillet-meal', 'keto-friendly', 'comfort-food'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/creamy-garlic-butter-tuscan-chicken/hero.webp',
      altText: 'Creamy Garlic Butter Tuscan Chicken in skillet',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 480,
      proteinGrams: 42,
      carbsGrams: 8,
      fatGrams: 32,
      sodiumMg: 520,
    },
    recipeCardData: {
      storageInstructions: 'Store leftovers in an airtight glass container in the refrigerator for up to 3 days.',
      reheatingInstructions: 'Reheat gently in a skillet over low heat with a splash of chicken broth or cream to loosen sauce.',
      chefTips: [
        'Use freshly grated Parmesan from a block for a silky sauce that will not separate.',
        'Cut thick chicken breasts horizontally into cutlets to ensure even, fast cooking.',
      ],
      substitutions: [
        { original: 'Heavy cream', substitute: 'Full-fat canned coconut milk', note: 'For dairy-free option' },
        { original: 'Sun-dried tomatoes', substitute: 'Halved cherry tomatoes', note: 'For a lighter flavor profile' },
      ],
      servingPairings: ['Buttery egg noodles', 'Crispy roasted garlic bread', 'Steamed green beans', 'Mashed potatoes'],
      whyYoullLoveThis: [
        'Ready from start to finish in 30 minutes',
        'Made in one single skillet for easy cleanup',
        'Rich, restaurant-caliber cream sauce',
        'Naturally low-carb and gluten-free friendly',
      ],
    },
    faq: [
      { question: 'Can I use chicken thighs instead of breasts?', answer: 'Yes! Boneless skinless chicken thighs work wonderfully and stay extra juicy. Cook for 5-6 minutes per side.' },
      { question: 'Can I freeze this recipe?', answer: 'Because of the heavy cream sauce, freezing is not recommended as dairy sauces can split upon thawing.' },
    ],
    editorialStyle: 'quick-easy',
    seoTitle: 'Creamy Garlic Butter Tuscan Chicken (30-Minute Dinner)',
    metaDescription: 'An easy 30-minute Tuscan chicken recipe with sun-dried tomatoes, spinach, and garlic cream sauce made in one skillet.',
    canonicalUrl: 'https://flavornest.xyz/recipes/creamy-garlic-butter-tuscan-chicken',
    status: 'published',
    createdAt: '2026-08-15T12:00:00Z',
    updatedAt: '2026-08-15T12:00:00Z',
    publishedAt: '2026-08-15T12:00:00Z',
    trending: true,
    featured: true,
  },
  {
    id: 'rec_crispy_air_fryer_wings_02',
    title: 'Ultra-Crispy Air Fryer Garlic Parmesan Wings',
    slug: 'ultra-crispy-air-fryer-garlic-parmesan-wings',
    shortDescription:
      'Extra crispy chicken wings cooked in the air fryer, then tossed in melted garlic butter, fresh herbs, and parmesan.',
    introduction:
      'Skip the deep fryer! These air fryer garlic parmesan wings get impossibly crispy on the outside while staying succulent and juicy on the inside, all in under 30 minutes.',
    ingredients: [
      { id: '1', rawText: '2 lbs chicken wings, split into flats and drumettes', item: 'Chicken wings', quantity: 2, unit: 'lbs' },
      { id: '2', rawText: '1 tbsp baking powder (aluminum-free)', item: 'Baking powder', quantity: 1, unit: 'tbsp' },
      { id: '3', rawText: '1 tsp garlic powder', item: 'Garlic powder', quantity: 1, unit: 'tsp' },
      { id: '4', rawText: '1 tsp onion powder', item: 'Onion powder', quantity: 1, unit: 'tsp' },
      { id: '5', rawText: '1/2 tsp kosher salt', item: 'Kosher salt', quantity: 0.5, unit: 'tsp' },
      { id: '6', rawText: '4 tbsp unsalted butter, melted', item: 'Melted butter', quantity: 4, unit: 'tbsp' },
      { id: '7', rawText: '4 cloves garlic, finely minced', item: 'Minced garlic', quantity: 4, unit: 'cloves' },
      { id: '8', rawText: '1/2 cup finely grated Parmesan cheese', item: 'Parmesan', quantity: 0.5, unit: 'cup' },
      { id: '9', rawText: '2 tbsp fresh parsley, chopped', item: 'Parsley', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Dry & Season Wings',
        instructionText: 'Pat the chicken wings completely dry with paper towels. In a large bowl, toss wings with baking powder, garlic powder, onion powder, and salt until evenly coated.',
        tip: 'Aluminum-free baking powder alters the skin pH for maximum crunch without deep frying.',
      },
      {
        stepNumber: 2,
        title: 'Air Fry Wings',
        instructionText: 'Preheat air fryer to 380°F (195°C). Arrange wings in a single layer in the basket with space between them. Cook for 20 minutes, flipping halfway.',
      },
      {
        stepNumber: 3,
        title: 'Crisp at High Heat',
        instructionText: 'Increase air fryer temperature to 400°F (200°C) and cook for an additional 4-5 minutes until deeply golden and blistered crisp.',
      },
      {
        stepNumber: 4,
        title: 'Toss in Garlic Parmesan Butter',
        instructionText: 'In a large bowl, whisk melted butter and minced garlic. Add the hot wings, grated parmesan, and chopped parsley. Toss vigorously to coat and serve immediately.',
      },
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 25,
    totalTimeMinutes: 30,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'American',
    mealType: 'dinner',
    cookingMethod: 'air-fryer',
    primaryCategorySlug: 'air-fryer',
    categorySlugs: ['air-fryer', 'chicken', '30-minute-meals', 'quick-and-easy'],
    tags: ['air-fryer', 'chicken-wings', 'game-day', '30-minute', 'garlic-parmesan'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/ultra-crispy-air-fryer-garlic-parmesan-wings/hero.webp',
      altText: 'Crispy Garlic Parmesan Air Fryer Wings',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 420,
      proteinGrams: 34,
      carbsGrams: 2,
      fatGrams: 30,
      sodiumMg: 490,
    },
    recipeCardData: {
      storageInstructions: 'Keep in an airtight container in the fridge for up to 4 days.',
      reheatingInstructions: 'Reheat in the air fryer at 380°F for 4-5 minutes to restore original crispiness.',
      chefTips: ['Do not overcrowd the air fryer basket; air circulation is key to crispiness.'],
      substitutions: [{ original: 'Parmesan', substitute: 'Pecorino Romano', note: 'Adds a sharper, saltier kick' }],
      servingPairings: ['Crisp celery & carrot sticks', 'Creamy ranch or blue cheese dip', 'French fries'],
      whyYoullLoveThis: [
        'Crispy without oil splatters or deep frying',
        'Ready in exactly 30 minutes',
        'Tossed in irresistible real garlic butter and parmesan',
      ],
    },
    editorialStyle: 'quick-easy',
    seoTitle: 'Crispy Air Fryer Garlic Parmesan Wings (30 Mins)',
    metaDescription: 'How to make the crispiest air fryer garlic parmesan wings with a secret baking powder trick. Juicy inside, crunchy outside.',
    canonicalUrl: 'https://flavornest.xyz/recipes/ultra-crispy-air-fryer-garlic-parmesan-wings',
    status: 'published',
    createdAt: '2026-08-16T14:00:00Z',
    updatedAt: '2026-08-16T14:00:00Z',
    publishedAt: '2026-08-16T14:00:00Z',
    trending: true,
  },
  {
    id: 'rec_one_pot_creamy_tomato_pasta_03',
    title: 'One-Pot 20-Minute Creamy Tomato Basil Pasta',
    slug: 'one-pot-creamy-tomato-basil-pasta',
    shortDescription:
      'Rigatoni cooked directly in a rich garlic tomato broth with cream, melted mozzarella, and fresh basil in 20 minutes.',
    introduction:
      'This cozy one-pot pasta cooks the pasta directly in the tomato broth, infusing every noodle with deep savory flavor and creating a naturally silky, starch-enriched sauce without draining a colander.',
    ingredients: [
      { id: '1', rawText: '1 lb rigatoni or penne pasta', item: 'Rigatoni pasta', quantity: 1, unit: 'lb' },
      { id: '2', rawText: '1 tbsp extra virgin olive oil', item: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { id: '3', rawText: '1 medium yellow onion, diced', item: 'Yellow onion', quantity: 1, unit: 'onion' },
      { id: '4', rawText: '4 cloves garlic, minced', item: 'Garlic', quantity: 4, unit: 'cloves' },
      { id: '5', rawText: '1 can (28 oz) crushed San Marzano tomatoes', item: 'Crushed tomatoes', quantity: 28, unit: 'oz' },
      { id: '6', rawText: '3 1/2 cups vegetable or chicken broth', item: 'Broth', quantity: 3.5, unit: 'cups' },
      { id: '7', rawText: '1/2 cup heavy cream', item: 'Heavy cream', quantity: 0.5, unit: 'cup' },
      { id: '8', rawText: '1 cup fresh mozzarella pearls or shredded mozzarella', item: 'Mozzarella', quantity: 1, unit: 'cup' },
      { id: '9', rawText: '1/2 cup fresh basil leaves, torn', item: 'Fresh basil', quantity: 0.5, unit: 'cup' },
      { id: '10', rawText: 'Salt, red pepper flakes, and black pepper to taste', item: 'Seasonings' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Sauté Aromatics',
        instructionText: 'Heat olive oil in a Dutch oven over medium heat. Sauté diced onion for 3-4 minutes until softened. Add garlic and red pepper flakes; cook for 1 minute.',
      },
      {
        stepNumber: 2,
        title: 'Add Pasta and Liquids',
        instructionText: 'Add uncooked rigatoni, crushed tomatoes, and broth to the pot. Stir well, making sure pasta is submerged. Bring to a boil.',
      },
      {
        stepNumber: 3,
        title: 'Simmer Pasta to Al Dente',
        instructionText: 'Reduce heat to medium-low, cover, and simmer for 11-13 minutes, stirring every few minutes to prevent sticking, until pasta is al dente and sauce is reduced.',
      },
      {
        stepNumber: 4,
        title: 'Stir in Cream and Cheese',
        instructionText: 'Remove lid, stir in heavy cream, mozzarella, and fresh basil. Let sit 2 minutes until cheese melts into luscious strings. Serve hot.',
      },
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    totalTimeMinutes: 20,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Italian',
    mealType: 'dinner',
    cookingMethod: 'one-pot',
    primaryCategorySlug: 'pasta',
    categorySlugs: ['pasta', 'one-pot-meals', 'quick-and-easy', '30-minute-meals'],
    tags: ['pasta', 'one-pot', 'vegetarian-friendly', '20-minute', 'comfort-food'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1621996346565-e3d5d628169b?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/one-pot-creamy-tomato-basil-pasta/hero.webp',
      altText: 'One Pot Creamy Tomato Basil Pasta',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 510,
      proteinGrams: 18,
      carbsGrams: 68,
      fatGrams: 19,
      sodiumMg: 610,
    },
    recipeCardData: {
      storageInstructions: 'Refrigerate in a sealed container up to 4 days.',
      reheatingInstructions: 'Reheat on the stove with 2 tablespoons of water or milk to loosen sauce.',
      chefTips: ['Stir periodically while pasta simmers to prevent noodles from sticking to the bottom of the pot.'],
      substitutions: [{ original: 'Heavy cream', substitute: 'Cream cheese (4 oz)', note: 'Gives a richer, tangy creaminess' }],
      servingPairings: ['Garlic cheese bread', 'Caesar salad', 'Roasted broccoli'],
      whyYoullLoveThis: [
        'Only one pot to wash',
        '20 minutes from start to table',
        'Rich tomato cream sauce made with pantry staples',
      ],
    },
    editorialStyle: 'quick-easy',
    seoTitle: '20-Minute One-Pot Creamy Tomato Basil Pasta',
    metaDescription: 'Easy one-pot creamy tomato pasta recipe ready in 20 minutes. No straining noodles needed. Comfort food made fast.',
    canonicalUrl: 'https://flavornest.xyz/recipes/one-pot-creamy-tomato-basil-pasta',
    status: 'published',
    createdAt: '2026-08-17T10:00:00Z',
    updatedAt: '2026-08-17T10:00:00Z',
    publishedAt: '2026-08-17T10:00:00Z',
    trending: true,
  },
  {
    id: 'rec_sheet_pan_salmon_04',
    title: 'Sheet Pan Lemon Herb Butter Salmon & Asparagus',
    slug: 'sheet-pan-lemon-herb-butter-salmon-asparagus',
    shortDescription:
      'Flaky baked salmon fillets and tender asparagus spears tossed in lemon garlic herb butter on a single sheet pan.',
    introduction:
      'Healthy, vibrant, and effortless. This sheet pan salmon dinner pairs tender Atlantic salmon with crisp roasted asparagus, all drizzled with melted lemon dill butter for maximum flavor with minimal effort.',
    ingredients: [
      { id: '1', rawText: '4 center-cut salmon fillets (approx 6 oz each)', item: 'Salmon fillets', quantity: 4, unit: 'fillets' },
      { id: '2', rawText: '1 lb fresh asparagus, woody ends trimmed', item: 'Asparagus', quantity: 1, unit: 'lb' },
      { id: '3', rawText: '3 tbsp unsalted butter, melted', item: 'Melted butter', quantity: 3, unit: 'tbsp' },
      { id: '4', rawText: '2 tbsp olive oil', item: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: '5', rawText: '3 cloves garlic, minced', item: 'Garlic', quantity: 3, unit: 'cloves' },
      { id: '6', rawText: '1 fresh lemon, juiced + 1 lemon sliced', item: 'Lemon', quantity: 2, unit: 'lemons' },
      { id: '7', rawText: '1 tbsp fresh dill or parsley, chopped', item: 'Fresh herbs', quantity: 1, unit: 'tbsp' },
      { id: '8', rawText: 'Salt and black pepper to taste', item: 'Salt and pepper' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Preheat and Prep Pan',
        instructionText: 'Preheat oven to 400°F (200°C). Line a large rimmed baking sheet with parchment paper.',
      },
      {
        stepNumber: 2,
        title: 'Season Asparagus and Salmon',
        instructionText: 'Place asparagus on the baking sheet, drizzle with 1 tbsp olive oil, and season with salt and pepper. Arrange salmon fillets skin-side down alongside the asparagus.',
      },
      {
        stepNumber: 3,
        title: 'Drizzle Lemon Herb Butter',
        instructionText: 'Whisk melted butter, remaining olive oil, minced garlic, lemon juice, and chopped dill. Spoon generously over the salmon fillets and asparagus. Top salmon with lemon slices.',
      },
      {
        stepNumber: 4,
        title: 'Bake to Flaky Perfection',
        instructionText: 'Bake for 12-14 minutes until salmon easily flakes with a fork (internal temp 135-140°F) and asparagus is tender-crisp. Serve warm.',
      },
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 14,
    totalTimeMinutes: 24,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Mediterranean',
    mealType: 'dinner',
    cookingMethod: 'baking',
    primaryCategorySlug: '30-minute-meals',
    categorySlugs: ['30-minute-meals', 'quick-and-easy'],
    tags: ['salmon', 'sheet-pan', 'healthy', 'low-carb', '25-minute'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/sheet-pan-lemon-herb-butter-salmon-asparagus/hero.webp',
      altText: 'Sheet Pan Lemon Herb Butter Salmon',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 390,
      proteinGrams: 36,
      carbsGrams: 5,
      fatGrams: 26,
      sodiumMg: 380,
    },
    editorialStyle: 'quick-easy',
    seoTitle: '20-Minute Sheet Pan Lemon Herb Salmon & Asparagus',
    metaDescription: 'A healthy and easy sheet pan salmon dinner with asparagus, lemon, and garlic butter. Clean eating in under 25 minutes.',
    canonicalUrl: 'https://flavornest.xyz/recipes/sheet-pan-lemon-herb-butter-salmon-asparagus',
    status: 'published',
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-18T10:00:00Z',
    publishedAt: '2026-08-18T10:00:00Z',
    trending: true,
  },
  {
    id: 'rec_slow_cooker_beef_pot_roast_05',
    title: 'Melt-in-Your-Mouth Slow Cooker Beef Pot Roast',
    slug: 'melt-in-your-mouth-slow-cooker-beef-pot-roast',
    shortDescription:
      'Fork-tender beef chuck roast braised low and slow with carrots, baby red potatoes, onions, and rich rosemary gravy.',
    introduction:
      'The ultimate set-it-and-forget-it family dinner. A marbled beef chuck roast simmers all day with baby potatoes, sweet carrots, and aromatics, resulting in ultra-tender beef and a deeply savory homemade gravy.',
    ingredients: [
      { id: '1', rawText: '3-4 lb boneless beef chuck roast, trimmed of excess fat', item: 'Beef chuck roast', quantity: 3.5, unit: 'lbs' },
      { id: '2', rawText: '2 tbsp olive oil', item: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: '3', rawText: '1 lb baby red potatoes, halved', item: 'Baby potatoes', quantity: 1, unit: 'lb' },
      { id: '4', rawText: '1 lb carrots, peeled and cut into 2-inch chunks', item: 'Carrots', quantity: 1, unit: 'lb' },
      { id: '5', rawText: '1 large yellow onion, quartered', item: 'Yellow onion', quantity: 1, unit: 'onion' },
      { id: '6', rawText: '4 cloves garlic, smashed', item: 'Garlic', quantity: 4, unit: 'cloves' },
      { id: '7', rawText: '2 cups low-sodium beef bone broth', item: 'Beef broth', quantity: 2, unit: 'cups' },
      { id: '8', rawText: '2 tbsp Worcestershire sauce', item: 'Worcestershire sauce', quantity: 2, unit: 'tbsp' },
      { id: '9', rawText: '2 sprigs fresh rosemary & 3 sprigs fresh thyme', item: 'Fresh herbs' },
      { id: '10', rawText: '1 tbsp kosher salt and 1 tsp freshly ground black pepper', item: 'Seasonings' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Sear the Roast',
        instructionText: 'Pat roast dry and season liberally with kosher salt and black pepper. Heat olive oil in a large skillet over high heat. Sear the meat for 3-4 minutes per side until a deep dark brown crust forms.',
        tip: 'Deep searing builds rich caramelized umami flavor in the finished gravy.',
      },
      {
        stepNumber: 2,
        title: 'Assemble in Slow Cooker',
        instructionText: 'Place carrots, baby potatoes, and quartered onions at the bottom of the slow cooker insert. Place the seared chuck roast directly on top of the vegetables.',
      },
      {
        stepNumber: 3,
        title: 'Add Broth & Aromatics',
        instructionText: 'Pour beef broth and Worcestershire sauce around the roast. Nest fresh rosemary and thyme sprigs around the meat.',
      },
      {
        stepNumber: 4,
        title: 'Slow Cook to Fork-Tender',
        instructionText: 'Cover and cook on LOW for 8-9 hours (or HIGH for 5-6 hours) until the beef easily falls apart with a fork. Discard herb stems, shred beef, and spoon pan gravy over meat and vegetables.',
      },
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 480,
    totalTimeMinutes: 495,
    servings: 6,
    difficulty: 'easy',
    cuisine: 'American',
    mealType: 'dinner',
    cookingMethod: 'slow-cooker',
    primaryCategorySlug: 'beef',
    categorySlugs: ['beef', 'slow-cooker'],
    tags: ['beef', 'pot-roast', 'slow-cooker', 'comfort-food', 'family-favorite'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/melt-in-your-mouth-slow-cooker-beef-pot-roast/hero.webp',
      altText: 'Slow Cooker Beef Pot Roast',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 580,
      proteinGrams: 48,
      carbsGrams: 28,
      fatGrams: 30,
      sodiumMg: 690,
    },
    editorialStyle: 'comfort-food',
    seoTitle: 'Melt-in-Your-Mouth Slow Cooker Pot Roast Recipe',
    metaDescription: 'Easy slow cooker beef pot roast with tender carrots, potatoes, and savory gravy. Slow braised chuck roast perfection.',
    canonicalUrl: 'https://flavornest.xyz/recipes/melt-in-your-mouth-slow-cooker-beef-pot-roast',
    status: 'published',
    createdAt: '2026-08-19T09:00:00Z',
    updatedAt: '2026-08-19T09:00:00Z',
    publishedAt: '2026-08-19T09:00:00Z',
  },
  {
    id: 'rec_honey_garlic_chicken_bites_06',
    title: '20-Minute Sticky Honey Garlic Chicken Bites',
    slug: '20-minute-sticky-honey-garlic-chicken-bites',
    shortDescription:
      'Crispy pan-fried chicken breast cubes coated in a sweet, savory, and sticky garlic soy glaze over fluffy jasmine rice.',
    introduction:
      'Better than takeout and done in 20 flat minutes. Bite-sized chicken breast pieces are lightly dusted and seared crisp, then tossed in a bubbling honey-garlic glaze.',
    ingredients: [
      { id: '1', rawText: '1.5 lbs boneless skinless chicken breasts, cut into 1-inch bite pieces', item: 'Chicken breasts', quantity: 1.5, unit: 'lbs' },
      { id: '2', rawText: '2 tbsp cornstarch', item: 'Cornstarch', quantity: 2, unit: 'tbsp' },
      { id: '3', rawText: '2 tbsp vegetable oil', item: 'Vegetable oil', quantity: 2, unit: 'tbsp' },
      { id: '4', rawText: '1/3 cup pure honey', item: 'Honey', quantity: 0.33, unit: 'cup' },
      { id: '5', rawText: '3 tbsp low-sodium soy sauce', item: 'Soy sauce', quantity: 3, unit: 'tbsp' },
      { id: '6', rawText: '5 cloves garlic, finely minced', item: 'Garlic', quantity: 5, unit: 'cloves' },
      { id: '7', rawText: '1 tbsp apple cider vinegar or rice vinegar', item: 'Vinegar', quantity: 1, unit: 'tbsp' },
      { id: '8', rawText: '1 tsp toasted sesame oil', item: 'Sesame oil', quantity: 1, unit: 'tsp' },
      { id: '9', rawText: 'Sesame seeds and sliced green onions for garnish', item: 'Garnish' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Coat & Sear Chicken',
        instructionText: 'Toss chicken pieces with cornstarch, salt, and pepper until lightly coated. Heat vegetable oil in a large skillet over medium-high heat. Sear chicken pieces for 6-8 minutes, turning until golden brown on all sides.',
      },
      {
        stepNumber: 2,
        title: 'Whisk Honey Garlic Sauce',
        instructionText: 'In a small bowl, whisk honey, soy sauce, minced garlic, vinegar, and sesame oil.',
      },
      {
        stepNumber: 3,
        title: 'Glaze and Thicken',
        instructionText: 'Pour sauce directly over the hot chicken in the skillet. Simmer vigorously for 2-3 minutes, stirring constantly until the sauce turns glossy and thickly coats the chicken.',
      },
      {
        stepNumber: 4,
        title: 'Garnish & Serve',
        instructionText: 'Remove from heat, sprinkle with toasted sesame seeds and sliced green onions, and serve immediately over steamed rice.',
      },
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    totalTimeMinutes: 20,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Asian-American',
    mealType: 'dinner',
    cookingMethod: 'stovetop',
    primaryCategorySlug: 'chicken',
    categorySlugs: ['chicken', 'quick-and-easy', '30-minute-meals'],
    tags: ['chicken', '20-minute', 'kid-friendly', 'takeout-fakeout', 'meal-prep'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1527477321055-436158a257a5?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/20-minute-sticky-honey-garlic-chicken-bites/hero.webp',
      altText: 'Sticky Honey Garlic Chicken Bites',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 360,
      proteinGrams: 38,
      carbsGrams: 24,
      fatGrams: 11,
      sodiumMg: 580,
    },
    editorialStyle: 'quick-easy',
    seoTitle: '20-Minute Sticky Honey Garlic Chicken Bites',
    metaDescription: 'Quick and delicious 20-minute honey garlic chicken recipe. Crispy chicken breast bites in a sweet and sticky homemade glaze.',
    canonicalUrl: 'https://flavornest.xyz/recipes/20-minute-sticky-honey-garlic-chicken-bites',
    status: 'published',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
    publishedAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'rec_blueberry_pancakes_07',
    title: 'Fluffy Golden Buttermilk Blueberry Pancakes',
    slug: 'fluffy-golden-buttermilk-blueberry-pancakes',
    shortDescription:
      'Extra thick, tall, and fluffy diner-style buttermilk pancakes bursting with juicy sweet blueberries and warm maple syrup.',
    introduction:
      'The definitive weekend breakfast recipe. These scratch-made pancakes use real buttermilk and a quick batter resting technique to create towering, ultra-tender pancakes with crispy golden edges.',
    ingredients: [
      { id: '1', rawText: '2 cups all-purpose flour', item: 'All-purpose flour', quantity: 2, unit: 'cups' },
      { id: '2', rawText: '2 tbsp granulated sugar', item: 'Sugar', quantity: 2, unit: 'tbsp' },
      { id: '3', rawText: '2 tsp baking powder', item: 'Baking powder', quantity: 2, unit: 'tsp' },
      { id: '4', rawText: '1/2 tsp baking soda', item: 'Baking soda', quantity: 0.5, unit: 'tsp' },
      { id: '5', rawText: '1/2 tsp fine sea salt', item: 'Sea salt', quantity: 0.5, unit: 'tsp' },
      { id: '6', rawText: '2 cups real buttermilk (room temp)', item: 'Buttermilk', quantity: 2, unit: 'cups' },
      { id: '7', rawText: '2 large eggs', item: 'Eggs', quantity: 2, unit: 'eggs' },
      { id: '8', rawText: '1/4 cup unsalted butter, melted and cooled', item: 'Melted butter', quantity: 0.25, unit: 'cup' },
      { id: '9', rawText: '1 tsp pure vanilla extract', item: 'Vanilla extract', quantity: 1, unit: 'tsp' },
      { id: '10', rawText: '1.5 cups fresh blueberries', item: 'Blueberries', quantity: 1.5, unit: 'cups' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Whisk Dry & Wet Separately',
        instructionText: 'In a large bowl, whisk flour, sugar, baking powder, baking soda, and salt. In a separate bowl, whisk buttermilk, eggs, melted butter, and vanilla.',
      },
      {
        stepNumber: 2,
        title: 'Gently Combine & Rest Batter',
        instructionText: 'Pour wet ingredients into dry ingredients. Stir with a wooden spoon until just combined; small lumps are normal! Let batter rest for 10 minutes to activate.',
        tip: 'Do not overmix! Overmixing develops gluten and makes pancakes rubbery instead of fluffy.',
      },
      {
        stepNumber: 3,
        title: 'Griddle Pancakes with Blueberries',
        instructionText: 'Heat a nonstick skillet or griddle over medium-low heat with a dab of butter. Pour 1/3 cup batter per pancake. Immediately scatter a handful of blueberries onto the wet batter.',
      },
      {
        stepNumber: 4,
        title: 'Flip and Serve',
        instructionText: 'Cook for 2-3 minutes until bubbles surface and edges look set. Flip and cook for another 1-2 minutes until golden. Stack high with butter and warm pure maple syrup.',
      },
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    totalTimeMinutes: 20,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'American',
    mealType: 'breakfast',
    cookingMethod: 'stovetop',
    primaryCategorySlug: 'breakfast',
    categorySlugs: ['breakfast', 'quick-and-easy'],
    tags: ['pancakes', 'breakfast', 'brunch', 'blueberries', 'family-favorite'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/fluffy-golden-buttermilk-blueberry-pancakes/hero.webp',
      altText: 'Fluffy Blueberry Pancakes with Maple Syrup',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 340,
      proteinGrams: 9,
      carbsGrams: 48,
      fatGrams: 12,
      sodiumMg: 420,
    },
    editorialStyle: 'family-favorite',
    seoTitle: 'Best Fluffy Buttermilk Blueberry Pancakes Recipe',
    metaDescription: 'How to make tall, extra fluffy buttermilk blueberry pancakes from scratch. Easy foolproof breakfast for lazy weekends.',
    canonicalUrl: 'https://flavornest.xyz/recipes/fluffy-golden-buttermilk-blueberry-pancakes',
    status: 'published',
    createdAt: '2026-08-21T08:00:00Z',
    updatedAt: '2026-08-21T08:00:00Z',
    publishedAt: '2026-08-21T08:00:00Z',
  },
  {
    id: 'rec_crispy_baby_potatoes_08',
    title: 'Crispy Garlic Butter Air Fryer Baby Potatoes',
    slug: 'crispy-garlic-butter-air-fryer-baby-potatoes',
    shortDescription:
      'Golden, crispy skins and creamy fluffy centers seasoned with garlic, smoked paprika, rosemary, and parmesan.',
    introduction:
      'The ultimate quick side dish. These baby Yukon gold potatoes roast to crunchy perfection in half the time of an oven, tossed in aromatic garlic herb butter.',
    ingredients: [
      { id: '1', rawText: '1.5 lbs baby Yukon gold or red potatoes, halved', item: 'Baby potatoes', quantity: 1.5, unit: 'lbs' },
      { id: '2', rawText: '1.5 tbsp olive oil', item: 'Olive oil', quantity: 1.5, unit: 'tbsp' },
      { id: '3', rawText: '2 tbsp butter, melted', item: 'Melted butter', quantity: 2, unit: 'tbsp' },
      { id: '4', rawText: '1 tsp garlic powder', item: 'Garlic powder', quantity: 1, unit: 'tsp' },
      { id: '5', rawText: '1/2 tsp smoked paprika', item: 'Smoked paprika', quantity: 0.5, unit: 'tsp' },
      { id: '6', rawText: '1 tsp fresh rosemary, minced', item: 'Rosemary', quantity: 1, unit: 'tsp' },
      { id: '7', rawText: '1/4 cup grated Parmesan cheese', item: 'Parmesan', quantity: 0.25, unit: 'cup' },
      { id: '8', rawText: '1/2 tsp kosher salt and black pepper', item: 'Seasonings' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Toss Potatoes in Seasoning',
        instructionText: 'Halve the washed baby potatoes. In a bowl, toss with olive oil, garlic powder, smoked paprika, salt, and pepper.',
      },
      {
        stepNumber: 2,
        title: 'Air Fry to Crispy Golden',
        instructionText: 'Preheat air fryer to 400°F (200°C). Place potatoes in the basket cut-side down. Cook for 18-20 minutes, shaking the basket at the 10-minute mark.',
      },
      {
        stepNumber: 3,
        title: 'Toss in Garlic Herb Butter',
        instructionText: 'Transfer hot crispy potatoes to a bowl, drizzle with melted butter, chopped rosemary, and grated parmesan. Toss and serve immediately.',
      },
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    totalTimeMinutes: 25,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'American',
    mealType: 'side-dish',
    cookingMethod: 'air-fryer',
    primaryCategorySlug: 'air-fryer',
    categorySlugs: ['air-fryer', 'quick-and-easy', '30-minute-meals'],
    tags: ['potatoes', 'air-fryer', 'side-dish', 'budget-friendly', '25-minute'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/crispy-garlic-butter-air-fryer-baby-potatoes/hero.webp',
      altText: 'Crispy Air Fryer Baby Potatoes with herbs',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 190,
      proteinGrams: 4,
      carbsGrams: 28,
      fatGrams: 8,
      sodiumMg: 280,
    },
    editorialStyle: 'budget-friendly',
    seoTitle: 'Crispy Garlic Butter Air Fryer Baby Potatoes (20 Mins)',
    metaDescription: 'Easy 20-minute air fryer baby potatoes with crispy skins and creamy centers. Tossed in garlic herb parmesan butter.',
    canonicalUrl: 'https://flavornest.xyz/recipes/crispy-garlic-butter-air-fryer-baby-potatoes',
    status: 'published',
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
    publishedAt: '2026-08-22T10:00:00Z',
  },
  {
    id: 'rec_apple_crisp_09',
    title: 'Classic Warm Cinnamon Spiced Apple Crisp',
    slug: 'classic-warm-cinnamon-spiced-apple-crisp',
    shortDescription:
      'Tender spiced Honeycrisp apples baked under a golden brown buttery brown sugar oat crumble topping with vanilla ice cream.',
    introduction:
      'The quintessential cozy dessert. Tart and sweet apples are tossed with cinnamon and nutmeg, then topped with a generous layer of buttery rolled oats and baked until bubbly and golden brown.',
    ingredients: [
      { id: '1', rawText: '6 medium Honeycrisp or Granny Smith apples, peeled, cored, and sliced', item: 'Apples', quantity: 6, unit: 'apples' },
      { id: '2', rawText: '2 tbsp granulated sugar', item: 'Sugar', quantity: 2, unit: 'tbsp' },
      { id: '3', rawText: '1.5 tsp ground cinnamon, divided', item: 'Cinnamon', quantity: 1.5, unit: 'tsp' },
      { id: '4', rawText: '1 tbsp lemon juice', item: 'Lemon juice', quantity: 1, unit: 'tbsp' },
      { id: '5', rawText: '1 cup old-fashioned rolled oats', item: 'Rolled oats', quantity: 1, unit: 'cup' },
      { id: '6', rawText: '1/2 cup all-purpose flour', item: 'Flour', quantity: 0.5, unit: 'cup' },
      { id: '7', rawText: '1/2 cup light brown sugar, packed', item: 'Brown sugar', quantity: 0.5, unit: 'cup' },
      { id: '8', rawText: '1/2 cup cold unsalted butter, cubed', item: 'Cold butter', quantity: 0.5, unit: 'cup' },
      { id: '9', rawText: '1/4 tsp ground nutmeg & 1/4 tsp salt', item: 'Spices' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Prep Apples',
        instructionText: 'Preheat oven to 350°F (175°C). Butter an 8x8-inch baking dish. Toss sliced apples with granulated sugar, lemon juice, and 1/2 tsp cinnamon. Spread evenly into the baking dish.',
      },
      {
        stepNumber: 2,
        title: 'Make Oat Crumble',
        instructionText: 'In a medium bowl, combine rolled oats, flour, brown sugar, remaining 1 tsp cinnamon, nutmeg, and salt. Cut in cold cubed butter with a pastry blender or fingers until crumbly pea-sized clusters form.',
      },
      {
        stepNumber: 3,
        title: 'Bake Until Bubbly & Crisp',
        instructionText: 'Scatter the oat topping evenly over the apples. Bake for 40-45 minutes until topping is deep golden and juices are bubbling around the edges. Let cool 10 minutes and serve warm with vanilla ice cream.',
      },
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 45,
    totalTimeMinutes: 60,
    servings: 6,
    difficulty: 'easy',
    cuisine: 'American',
    mealType: 'dessert',
    cookingMethod: 'baking',
    primaryCategorySlug: 'desserts',
    categorySlugs: ['desserts'],
    tags: ['dessert', 'apple-crisp', 'baking', 'comfort-food', 'fall-recipes'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/classic-warm-cinnamon-spiced-apple-crisp/hero.webp',
      altText: 'Warm Cinnamon Apple Crisp with Ice Cream',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 380,
      proteinGrams: 4,
      carbsGrams: 62,
      fatGrams: 16,
      sodiumMg: 120,
    },
    editorialStyle: 'comfort-food',
    seoTitle: 'Best Classic Cinnamon Spiced Apple Crisp Recipe',
    metaDescription: 'Easy homemade apple crisp with sweet cinnamon apples and crunchy brown sugar oat topping. Perfect warm dessert.',
    canonicalUrl: 'https://flavornest.xyz/recipes/classic-warm-cinnamon-spiced-apple-crisp',
    status: 'published',
    createdAt: '2026-08-23T15:00:00Z',
    updatedAt: '2026-08-23T15:00:00Z',
    publishedAt: '2026-08-23T15:00:00Z',
  },
  {
    id: 'rec_cheesy_ground_beef_pasta_10',
    title: 'Hearty One-Pot Cheesy Ground Beef Pasta',
    slug: 'hearty-one-pot-cheesy-ground-beef-pasta',
    shortDescription:
      'Savory seasoned ground beef and shell pasta simmered in rich tomato sauce and smothered in melted sharp cheddar cheese.',
    introduction:
      'The ultimate homemade version of hamburger helper, elevated with real ingredients, aromatic spices, and a creamy, melted cheddar finish that the whole family will request every week.',
    ingredients: [
      { id: '1', rawText: '1 lb lean ground beef (85/15)', item: 'Ground beef', quantity: 1, unit: 'lb' },
      { id: '2', rawText: '1 medium yellow onion, diced', item: 'Yellow onion', quantity: 1, unit: 'onion' },
      { id: '3', rawText: '3 cloves garlic, minced', item: 'Garlic', quantity: 3, unit: 'cloves' },
      { id: '4', rawText: '2 tbsp tomato paste', item: 'Tomato paste', quantity: 2, unit: 'tbsp' },
      { id: '5', rawText: '1 can (15 oz) tomato sauce', item: 'Tomato sauce', quantity: 15, unit: 'oz' },
      { id: '6', rawText: '2.5 cups beef broth', item: 'Beef broth', quantity: 2.5, unit: 'cups' },
      { id: '7', rawText: '8 oz medium pasta shells or macaroni', item: 'Pasta shells', quantity: 8, unit: 'oz' },
      { id: '8', rawText: '1/2 cup heavy cream or whole milk', item: 'Heavy cream', quantity: 0.5, unit: 'cup' },
      { id: '9', rawText: '2 cups freshly shredded sharp cheddar cheese', item: 'Cheddar cheese', quantity: 2, unit: 'cups' },
      { id: '10', rawText: '1 tsp Italian seasoning, 1 tsp onion powder, 1/2 tsp paprika, salt and pepper', item: 'Seasonings' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Brown Ground Beef',
        instructionText: 'In a large Dutch oven, brown ground beef and diced onion over medium heat until meat is no longer pink (6-7 minutes). Drain excess grease if necessary. Add garlic and tomato paste; cook 1 minute.',
      },
      {
        stepNumber: 2,
        title: 'Add Pasta and Liquids',
        instructionText: 'Pour in tomato sauce, beef broth, seasonings, and uncooked pasta shells. Stir well and bring to a boil.',
      },
      {
        stepNumber: 3,
        title: 'Simmer',
        instructionText: 'Cover with lid, reduce heat to medium-low, and simmer for 10-12 minutes until pasta is tender, stirring occasionally.',
      },
      {
        stepNumber: 4,
        title: 'Melt Cheese',
        instructionText: 'Remove lid, stir in heavy cream and shredded cheddar until completely melted into a rich creamy sauce. Garnish with chopped parsley and serve.',
      },
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    totalTimeMinutes: 25,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'American',
    mealType: 'dinner',
    cookingMethod: 'one-pot',
    primaryCategorySlug: 'beef',
    categorySlugs: ['beef', 'one-pot-meals', '30-minute-meals', 'quick-and-easy'],
    tags: ['ground-beef', 'one-pot', 'cheesy-pasta', 'family-favorite', '25-minute'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/hearty-one-pot-cheesy-ground-beef-pasta/hero.webp',
      altText: 'One Pot Cheesy Ground Beef Pasta Skillet',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 560,
      proteinGrams: 38,
      carbsGrams: 46,
      fatGrams: 26,
      sodiumMg: 680,
    },
    editorialStyle: 'family-favorite',
    seoTitle: 'One-Pot Cheesy Ground Beef Pasta (25-Minute Meal)',
    metaDescription: 'Easy 25-minute one-pot cheesy ground beef pasta skillet. A comforting homemade weeknight dinner the entire family loves.',
    canonicalUrl: 'https://flavornest.xyz/recipes/hearty-one-pot-cheesy-ground-beef-pasta',
    status: 'published',
    createdAt: '2026-08-24T12:00:00Z',
    updatedAt: '2026-08-24T12:00:00Z',
    publishedAt: '2026-08-24T12:00:00Z',
  },
  {
    id: 'rec_slow_cooker_wild_rice_soup_11',
    title: 'Cozy Slow Cooker Creamy Chicken Wild Rice Soup',
    slug: 'cozy-slow-cooker-creamy-chicken-wild-rice-soup',
    shortDescription:
      'Warm and comforting chicken breast and wild rice blend simmered with carrots, celery, herbs, and finished with rich cream.',
    introduction:
      'Pure comfort in a bowl. Nutty wild rice, tender shredded chicken, and aromatic vegetables simmer gently in a seasoned broth before being enriched with a velvety cream roux.',
    ingredients: [
      { id: '1', rawText: '1.5 lbs boneless skinless chicken breasts', item: 'Chicken breasts', quantity: 1.5, unit: 'lbs' },
      { id: '2', rawText: '1 cup uncooked wild rice blend (rinsed)', item: 'Wild rice blend', quantity: 1, unit: 'cup' },
      { id: '3', rawText: '1 medium yellow onion, finely diced', item: 'Yellow onion', quantity: 1, unit: 'onion' },
      { id: '4', rawText: '3 medium carrots, sliced into rounds', item: 'Carrots', quantity: 3, unit: 'carrots' },
      { id: '5', rawText: '3 ribs celery, sliced', item: 'Celery', quantity: 3, unit: 'ribs' },
      { id: '6', rawText: '4 cloves garlic, minced', item: 'Garlic', quantity: 4, unit: 'cloves' },
      { id: '7', rawText: '6 cups low-sodium chicken broth', item: 'Chicken broth', quantity: 6, unit: 'cups' },
      { id: '8', rawText: '1 tsp poultry seasoning & 1 tsp dried thyme', item: 'Herbs' },
      { id: '9', rawText: '4 tbsp butter + 1/3 cup all-purpose flour', item: 'Roux base' },
      { id: '10', rawText: '1.5 cups whole milk or half-and-half', item: 'Milk or cream', quantity: 1.5, unit: 'cups' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Add to Slow Cooker',
        instructionText: 'Add chicken breasts, rinsed wild rice, diced onion, carrots, celery, garlic, chicken broth, poultry seasoning, and thyme to the slow cooker insert. Stir gently.',
      },
      {
        stepNumber: 2,
        title: 'Slow Cook',
        instructionText: 'Cover and cook on LOW for 6-7 hours (or HIGH for 3.5-4 hours) until rice is tender and chicken shreds easily.',
      },
      {
        stepNumber: 3,
        title: 'Shred Chicken & Make Cream Roux',
        instructionText: 'Remove chicken and shred with two forks; return to slow cooker. In a saucepan, melt 4 tbsp butter, whisk in 1/3 cup flour for 1 minute, then slowly whisk in milk until smooth and thickened.',
      },
      {
        stepNumber: 4,
        title: 'Combine & Serve',
        instructionText: 'Stir the creamy roux into the slow cooker. Simmer 10 more minutes until soup is luxuriously thick. Season with salt and cracked black pepper to taste.',
      },
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 390,
    totalTimeMinutes: 405,
    servings: 6,
    difficulty: 'easy',
    cuisine: 'American',
    mealType: 'dinner',
    cookingMethod: 'slow-cooker',
    primaryCategorySlug: 'slow-cooker',
    categorySlugs: ['slow-cooker', 'chicken'],
    tags: ['soup', 'slow-cooker', 'chicken-soup', 'wild-rice', 'comfort-food'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/cozy-slow-cooker-creamy-chicken-wild-rice-soup/hero.webp',
      altText: 'Creamy Chicken Wild Rice Soup in bowl',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 430,
      proteinGrams: 32,
      carbsGrams: 38,
      fatGrams: 16,
      sodiumMg: 590,
    },
    editorialStyle: 'comfort-food',
    seoTitle: 'Cozy Slow Cooker Creamy Chicken Wild Rice Soup',
    metaDescription: 'The ultimate comforting slow cooker chicken wild rice soup with vegetables and creamy broth. Easy set-and-forget dinner.',
    canonicalUrl: 'https://flavornest.xyz/recipes/cozy-slow-cooker-creamy-chicken-wild-rice-soup',
    status: 'published',
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-08-25T14:00:00Z',
    publishedAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'rec_tuscan_sausage_gnocchi_12',
    title: 'Creamy Tuscan Sausage & Gnocchi Skillet',
    slug: 'creamy-tuscan-sausage-gnocchi-skillet',
    shortDescription:
      'Pillow-soft potato gnocchi and Italian sausage simmered in a sun-dried tomato garlic parmesan cream sauce in 25 minutes.',
    introduction:
      'Potato gnocchi cook directly in the savory pan sauce without pre-boiling! Paired with browned Italian sausage, baby spinach, and creamy parmesan, this is weeknight luxury.',
    ingredients: [
      { id: '1', rawText: '1 lb sweet or mild Italian sausage (casings removed)', item: 'Italian sausage', quantity: 1, unit: 'lb' },
      { id: '2', rawText: '1 lb shelf-stable potato gnocchi (uncooked)', item: 'Potato gnocchi', quantity: 1, unit: 'lb' },
      { id: '3', rawText: '1/2 cup sun-dried tomatoes in oil, chopped', item: 'Sun-dried tomatoes', quantity: 0.5, unit: 'cup' },
      { id: '4', rawText: '4 cloves garlic, minced', item: 'Garlic', quantity: 4, unit: 'cloves' },
      { id: '5', rawText: '1 cup chicken broth', item: 'Chicken broth', quantity: 1, unit: 'cup' },
      { id: '6', rawText: '3/4 cup heavy cream', item: 'Heavy cream', quantity: 0.75, unit: 'cup' },
      { id: '7', rawText: '1/2 cup grated Parmesan cheese', item: 'Parmesan', quantity: 0.5, unit: 'cup' },
      { id: '8', rawText: '2 cups fresh baby spinach', item: 'Baby spinach', quantity: 2, unit: 'cups' },
      { id: '9', rawText: '1 tsp Italian seasoning and pinch red pepper flakes', item: 'Seasonings' },
    ],
    instructions: [
      {
        stepNumber: 1,
        title: 'Brown Sausage',
        instructionText: 'In a large deep skillet over medium-high heat, cook Italian sausage, breaking it up with a wooden spoon until browned (5-6 minutes).',
      },
      {
        stepNumber: 2,
        title: 'Add Garlic, Tomatoes & Liquids',
        instructionText: 'Add garlic and sun-dried tomatoes; cook 1 minute. Pour in chicken broth, heavy cream, Italian seasoning, and red pepper flakes. Bring to a simmer.',
      },
      {
        stepNumber: 3,
        title: 'Cook Gnocchi in Sauce',
        instructionText: 'Add uncooked gnocchi directly into the bubbling liquid. Cover and simmer for 5-6 minutes, stirring once or twice until gnocchi are tender and pillowy.',
      },
      {
        stepNumber: 4,
        title: 'Fold in Spinach & Parmesan',
        instructionText: 'Remove lid, stir in grated parmesan and baby spinach until wilted into a silky sauce. Serve immediately.',
      },
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    totalTimeMinutes: 25,
    servings: 4,
    difficulty: 'easy',
    cuisine: 'Italian',
    mealType: 'dinner',
    cookingMethod: 'one-pot',
    primaryCategorySlug: 'pasta',
    categorySlugs: ['pasta', 'one-pot-meals', '30-minute-meals', 'quick-and-easy'],
    tags: ['gnocchi', 'italian-sausage', 'one-pan', '25-minute', 'comfort-food'],
    heroImage: {
      url: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=1200&q=80',
      r2Key: 'recipes/creamy-tuscan-sausage-gnocchi-skillet/hero.webp',
      altText: 'Creamy Sausage and Gnocchi Skillet with spinach',
      width: 1200,
      height: 800,
    },
    nutrition: {
      calories: 590,
      proteinGrams: 28,
      carbsGrams: 42,
      fatGrams: 35,
      sodiumMg: 780,
    },
    editorialStyle: 'quick-easy',
    seoTitle: '25-Minute Creamy Tuscan Sausage & Gnocchi Skillet',
    metaDescription: 'Easy one-pan creamy sausage gnocchi skillet with sun-dried tomatoes and spinach. No boiling water needed.',
    canonicalUrl: 'https://flavornest.xyz/recipes/creamy-tuscan-sausage-gnocchi-skillet',
    status: 'published',
    createdAt: '2026-08-26T12:00:00Z',
    updatedAt: '2026-08-26T12:00:00Z',
    publishedAt: '2026-08-26T12:00:00Z',
  },
];
