import { Category, PrimaryCategorySlug } from '../types/category';
import { RecipeEditorialAngle } from '../types/recipe';
import { EditorialStyleConfig } from '../types/editorial';

export const PRIMARY_CATEGORIES: Record<PrimaryCategorySlug, Category> = {
  'quick-and-easy': {
    id: 'cat_quick_easy',
    name: 'Quick & Easy',
    slug: 'quick-and-easy',
    description: 'Fast, minimal-prep recipes that deliver maximum flavor in record time for busy weeknights.',
    shortDescription: 'Delicious meals in 30 minutes or less with simple pantry staples.',
    heroImage: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80',
    iconName: 'Zap',
    sortOrder: 1,
    recipeCount: 12,
    featured: true,
  },
  'chicken': {
    id: 'cat_chicken',
    name: 'Chicken',
    slug: 'chicken',
    description: 'Juicy, seasoned, and dependable chicken recipes ranging from skillet dinners to crispy bakes.',
    shortDescription: 'Versatile chicken breast, thighs, and roast recipes the whole family will love.',
    heroImage: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
    iconName: 'ChefHat',
    sortOrder: 2,
    recipeCount: 18,
    featured: true,
  },
  'beef': {
    id: 'cat_beef',
    name: 'Beef',
    slug: 'beef',
    description: 'Hearty ground beef skillets, tender slow-cooked roasts, steaks, and comforting casseroles.',
    shortDescription: 'Satisfying beef dinners packed with rich, savory goodness.',
    heroImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    iconName: 'Flame',
    sortOrder: 3,
    recipeCount: 10,
    featured: false,
  },
  'pasta': {
    id: 'cat_pasta',
    name: 'Pasta',
    slug: 'pasta',
    description: 'Silky sauces, comforting baked dishes, and vibrant 20-minute pasta creations.',
    shortDescription: 'Classic Italian-inspired pasta dishes made simple for home kitchens.',
    heroImage: 'https://images.unsplash.com/photo-1621996346565-e3d5d628169b?auto=format&fit=crop&w=800&q=80',
    iconName: 'Utensils',
    sortOrder: 4,
    recipeCount: 14,
    featured: true,
  },
  'breakfast': {
    id: 'cat_breakfast',
    name: 'Breakfast',
    slug: 'breakfast',
    description: 'Make-ahead bakes, fluffy golden pancakes, egg skillets, and morning comfort foods.',
    shortDescription: 'Bright and energizing breakfast & brunch recipes for any day of the week.',
    heroImage: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
    iconName: 'Sun',
    sortOrder: 5,
    recipeCount: 8,
    featured: true,
  },
  'desserts': {
    id: 'cat_desserts',
    name: 'Desserts',
    slug: 'desserts',
    description: 'Irresistible cookies, warm fruit crisps, simple skillet cakes, and sweet treats.',
    shortDescription: 'Approachable dessert recipes that satisfy every sweet craving.',
    heroImage: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    iconName: 'Sparkles',
    sortOrder: 6,
    recipeCount: 9,
    featured: true,
  },
  'air-fryer': {
    id: 'cat_air_fryer',
    name: 'Air Fryer',
    slug: 'air-fryer',
    description: 'Ultra-crispy texture with less oil. From crispy wings to golden roasted potatoes.',
    shortDescription: 'Fast, crunchy, and effortless meals powered by your air fryer.',
    heroImage: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80',
    iconName: 'Wind',
    sortOrder: 7,
    recipeCount: 15,
    featured: true,
  },
  'slow-cooker': {
    id: 'cat_slow_cooker',
    name: 'Slow Cooker',
    slug: 'slow-cooker',
    description: 'Hands-off dump-and-go stews, pulled meats, and soul-warming comfort pots.',
    shortDescription: 'Set it, forget it, and come home to mouthwatering dinner aromas.',
    heroImage: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    iconName: 'Clock',
    sortOrder: 8,
    recipeCount: 11,
    featured: true,
  },
  'one-pot-meals': {
    id: 'cat_one_pot',
    name: 'One-Pot Meals',
    slug: 'one-pot-meals',
    description: 'Everything cooks together in one single skillet or pot for virtually zero cleanup.',
    shortDescription: 'Maximum flavor with minimal sink duty. The ultimate weeknight lifesaver.',
    heroImage: 'https://images.unsplash.com/photo-1584947897591-a5f1e8f855d0?auto=format&fit=crop&w=800&q=80',
    iconName: 'CookingPot',
    sortOrder: 9,
    recipeCount: 13,
    featured: true,
  },
  '30-minute-meals': {
    id: 'cat_30_min',
    name: '30-Minute Meals',
    slug: '30-minute-meals',
    description: 'From start to finish in 30 minutes or less without sacrificing fresh, bold taste.',
    shortDescription: 'Rapid dinners designed for real-world hectic schedules.',
    heroImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    iconName: 'Timer',
    sortOrder: 10,
    recipeCount: 16,
    featured: true,
  },
  'seasonal-recipes': {
    id: 'cat_seasonal',
    name: 'Seasonal Recipes',
    slug: 'seasonal-recipes',
    description: 'Cozy autumn braises, refreshing summer salads, and holiday-worthy feasts.',
    shortDescription: 'Celebrate peak seasonal produce and comforting holiday gatherings.',
    heroImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    iconName: 'Leaf',
    sortOrder: 11,
    recipeCount: 7,
    featured: false,
  },
};

export const EDITORIAL_STYLES: Record<RecipeEditorialAngle, EditorialStyleConfig> = {
  'quick-easy': {
    id: 'quick-easy',
    title: 'Quick & Easy',
    tagline: 'Simple steps, everyday ingredients, lightning-fast prep.',
    description: 'Focuses on efficiency, minimal cleanup, and smart shortcuts that do not compromise on taste.',
    targetAudience: 'Busy parents and working professionals needing fast weeknight dinner wins.',
    toneKeywords: ['Effortless', 'Fast', 'Stress-free', 'Streamlined'],
    badgeColorClass: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    accentBgClass: 'bg-emerald-500',
  },
  'comfort-food': {
    id: 'comfort-food',
    title: 'Comfort Food',
    tagline: 'Rich, warming, soul-satisfying home classics.',
    description: 'Focuses on deep savory depth, tender textures, and nostalgic heartwarming flavors.',
    targetAudience: 'Cooks craving cozy weekend meals and hearty family dinners.',
    toneKeywords: ['Hearty', 'Nostalgic', 'Savory', 'Warm', 'Indulgent'],
    badgeColorClass: 'bg-amber-50 text-amber-900 border-amber-200',
    accentBgClass: 'bg-amber-600',
  },
  'budget-friendly': {
    id: 'budget-friendly',
    title: 'Budget Friendly',
    tagline: 'Big taste on an affordable grocery bill.',
    description: 'Highlights affordable staples, zero-waste tips, and bulk ingredient utilization.',
    targetAudience: 'Budget-conscious families and students aiming to eat well for less.',
    toneKeywords: ['Economical', 'Smart-Pantry', 'Resourceful', 'Generous'],
    badgeColorClass: 'bg-teal-50 text-teal-800 border-teal-200',
    accentBgClass: 'bg-teal-600',
  },
  'family-favorite': {
    id: 'family-favorite',
    title: 'Family Favorite',
    tagline: 'Crowd-pleasing flavors tested for picky eaters of all ages.',
    description: 'Focuses on mild yet rich profiles, scalable batches, and customizable toppings.',
    targetAudience: 'Parents cooking for households with varied palates.',
    toneKeywords: ['Crowd-Pleaser', 'Kid-Approved', 'Satisfying', 'Balanced'],
    badgeColorClass: 'bg-orange-50 text-orange-900 border-orange-200',
    accentBgClass: 'bg-brand-500',
  },
  'beginner-friendly': {
    id: 'beginner-friendly',
    title: 'Beginner Friendly',
    tagline: 'Foolproof instructions with zero intimidating culinary jargon.',
    description: 'Includes clear visual cues, temperature guides, and simple kitchen recovery tips.',
    targetAudience: 'New home cooks building confidence in the kitchen.',
    toneKeywords: ['Foolproof', 'Accessible', 'Step-by-Step', 'Encouraging'],
    badgeColorClass: 'bg-sky-50 text-sky-800 border-sky-200',
    accentBgClass: 'bg-sky-500',
  },
  'meal-prep': {
    id: 'meal-prep',
    title: 'Meal Prep',
    tagline: 'Cook once, enjoy mouthwatering leftovers all week.',
    description: 'Features storage safety, freeze/thaw instructions, and modular reheats.',
    targetAudience: 'Organized individuals prepping weekly lunches or freezer stash dinners.',
    toneKeywords: ['Batch-Friendly', 'Storage-Ready', 'Efficient', 'Make-Ahead'],
    badgeColorClass: 'bg-slate-100 text-slate-800 border-slate-300',
    accentBgClass: 'bg-slate-600',
  },
  'seasonal-occasion': {
    id: 'seasonal-occasion',
    title: 'Seasonal / Occasion',
    tagline: 'Celebrate peak harvest and memorable gatherings.',
    description: 'Highlights fresh seasonal herbs, holiday-table presentation, and festive menus.',
    targetAudience: 'Entertainers and home chefs cooking for special events or peak harvest seasons.',
    toneKeywords: ['Vibrant', 'Festive', 'Harvest-Fresh', 'Celebratory'],
    badgeColorClass: 'bg-rose-50 text-rose-900 border-rose-200',
    accentBgClass: 'bg-rose-600',
  },
};
